# fly.toml app configuration file generated for resumeio-to-pdf on 2023-11-26T20:19:30-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "resumeio-to-pdf"
primary_region = "ams"

[build]

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  internal_port = 8_000
  min_machines_running = 0
  processes = [ "app" ]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory = "2gb"
  memory_mb = 2_048
